// Generated by CoffeeScript 1.6.2
(function() {
  var extract, gatherer, iter, load, request;

  gatherer = require('../gatherer');

  load = require('../load');

  request = require('../request');

  module.exports = function(details, callback) {
    var url;

    url = gatherer.card.url('Printings.aspx', details);
    request({
      url: url,
      followRedirect: false
    }, function(err, res, body) {
      if (res.statusCode !== 200) {
        if (err == null) {
          err = new Error('unexpected status code');
        }
      }
      if (err) {
        return callback(err);
      } else {
        return callback(null, extract(body));
      }
    });
  };

  iter = function(row, fn) {
    var _results;

    _results = [];
    while (row.hasClass('cardItem')) {
      fn(row, row.children().map(function() {
        return gatherer._get_text(this);
      }));
      if (row.next() === row) {
        break;
      }
      _results.push(row = row.next());
    }
    return _results;
  };

  extract = function(html) {
    var $, data, prefix;

    $ = load(html);
    data = {
      legality: {},
      versions: {}
    };
    prefix = '#ctl00_ctl00_ctl00_MainContent_SubContent_SubContent';
    iter($("" + prefix + "_PrintingsList_listRepeater_ctl00_cardTitle").parent().parent(), function(row, _arg) {
      var block, expansion, id, match, name, rarity, symbol, _ref;

      name = _arg[0], symbol = _arg[1], expansion = _arg[2], block = _arg[3];
      id = /\d+$/.exec(row.find('a').attr('href'))[0];
      _ref = /[(](.+)[)]/.exec(row.find('img').attr('alt')), match = _ref[0], rarity = _ref[1];
      return data.versions[id] = {
        expansion: expansion,
        rarity: rarity
      };
    });
    iter($("" + prefix + "_LegalityList_listRepeater_ctl00_ConditionTableData").parent(), function(row, _arg) {
      var conditions, format, legality;

      format = _arg[0], legality = _arg[1], conditions = _arg[2];
      return data.legality[format] = legality === 'Special' ? "" + legality + ": " + conditions : legality;
    });
    return data;
  };

}).call(this);
