// Generated by CoffeeScript 1.6.2
(function() {
  var epipeFilter, formatters, program, tutor;

  formatters = require('./formatters');

  tutor = require('./tutor');

  epipeFilter = function(err) {
    if (err.code === 'EPIPE') {
      process.exit();
    }
    if (process.stdout.listeners('error').length <= 1) {
      process.stdout.removeAllListeners();
      process.stdout.emit('error', err);
      return process.stdout.on('error', epipeFilter);
    }
  };

  process.stdout.on('error', epipeFilter);

  program = require('commander');

  program.version(require('../package').version);

  program.command('card <name|id>').description("output the given card's details").option('-f, --format [formatter]', 'Use this output format. Options are: summary (default), json', 'summary').action(function(name, options) {
    var id;

    if (/^\d+$/.test(name)) {
      id = name;
      return tutor.card({
        id: id
      }, formatters.card[options.format]);
    } else {
      return tutor.card({
        name: name
      }, formatters.card[options.format]);
    }
  });

  program.command('set <name>').description('output one page of cards from the named set').option('-p, --page [number]', 'specify page number', 1).action(function(name, options) {
    return tutor.set({
      name: name,
      page: options.page
    }, formatters.set);
  });

  module.exports = program;

}).call(this);
