// Generated by CoffeeScript 1.6.2
(function() {
  var epipeFilter, formatters, program, tutor;

  formatters = require('./formatters');

  tutor = require('./tutor');

  epipeFilter = function(err) {
    if (err.code === 'EPIPE') {
      process.exit();
    }
    if (process.stdout.listeners('error').length <= 1) {
      process.stdout.removeAllListeners();
      process.stdout.emit('error', err);
      return process.stdout.on('error', epipeFilter);
    }
  };

  process.stdout.on('error', epipeFilter);

  program = require('commander');

  program.version(require('../package').version);

  program.command('card <name>').description("output the named card's details").action(function(name) {
    return tutor.card({
      name: name
    }, formatters.card);
  });

  program.command('set <name>').description('output one page of cards from the named set').option('-p, --page [number]', 'specify page number', 1).action(function(name, options) {
    return tutor.set({
      name: name,
      page: options.page
    }, formatters.set);
  });

  module.exports = program;

}).call(this);
