// Generated by CoffeeScript 1.6.3
(function() {
  var exportFormatter, formatCard, join, withCaution;

  withCaution = function(view) {
    return function(err, res) {
      if (err === null) {
        console.log(view(res));
        return process.exit(0);
      } else if (err.errno === 'ENOTFOUND') {
        console.error('cannot connect to gatherer');
        return process.exit(1);
      } else {
        console.error("" + err);
        return process.exit(1);
      }
    };
  };

  join = function(array) {
    return array.join('\n');
  };

  formatCard = function(card) {
    var output;
    output = "" + card.name;
    if ('mana_cost' in card) {
      output += " " + card.mana_cost;
    }
    if ('power' in card) {
      output += " " + card.power + "/" + card.toughness;
    }
    if (card.text) {
      output += " " + (card.text.replace(/[\n\r]+/g, ' '));
    }
    return output;
  };

  exportFormatter = function(name, formatter) {
    return module.exports[name] = {
      json: withCaution(JSON.stringify),
      summary: withCaution(formatter)
    };
  };

  exportFormatter('formats', join);

  exportFormatter('sets', join);

  exportFormatter('types', join);

  exportFormatter('card', formatCard);

  exportFormatter('set', function(cards) {
    return join(cards.map(formatCard));
  });

}).call(this);
