// Generated by CoffeeScript 1.6.2
(function() {
  var printCard, printSet, withCaution;

  withCaution = function(view) {
    return function(err, res) {
      if (err === null) {
        return view(res);
      } else if (err.errno === 'ENOTFOUND') {
        return console.error('cannot connect to gatherer');
      } else {
        return console.error("" + err);
      }
    };
  };

  printCard = function(card) {
    var output;

    output = "" + card.name;
    if ('mana_cost' in card) {
      output += " " + card.mana_cost;
    }
    if ('power' in card) {
      output += " " + card.power + "/" + card.toughness;
    }
    if (card.text) {
      output += " " + (card.text.replace(/[\n\r]+/g, ' '));
    }
    return console.log(output);
  };

  printSet = function(cards) {
    var card, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = cards.length; _i < _len; _i++) {
      card = cards[_i];
      _results.push(printCard(card));
    }
    return _results;
  };

  module.exports = {
    card: {
      json: withCaution(function(card) {
        return console.log(JSON.stringify(card));
      }),
      summary: withCaution(printCard)
    },
    set: {
      json: withCaution(function(cards) {
        return console.log(JSON.stringify(cards));
      }),
      summary: withCaution(printSet)
    }
  };

}).call(this);
