// Generated by CoffeeScript 1.6.2
(function() {
  var code, name, _i, _len, _ref, _ref1;

  _ref = [['de', 'German'], ['en', 'English'], ['es', 'Spanish'], ['fr', 'French'], ['it', 'Italian'], ['ja', 'Japanese'], ['kr', 'Korean'], ['pt-BR', 'Portuguese'], ['pt-BR', 'Portuguese (Brazil)'], ['ru', 'Russian'], ['zh-CN', 'Chinese Traditional'], ['zh-TW', 'Chinese Simplified']];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    _ref1 = _ref[_i], code = _ref1[0], name = _ref1[1];
    exports[name] = code;
  }

}).call(this);
