// Generated by CoffeeScript 1.6.2
(function() {
  var gatherer, url,
    __slice = [].slice;

  gatherer = require('./gatherer');

  url = require('./url');

  module.exports = function($container) {
    var $links, $selected, numbers;

    $links = $container.children('a');
    $selected = $links.filter('[style="text-decoration:underline;"]');
    numbers = $links.map(function() {
      return +url.parse(this.attr('href'), true).query.page + 1;
    });
    return {
      min: Math.min.apply(Math, [1].concat(__slice.call(numbers))),
      max: Math.max.apply(Math, [1].concat(__slice.call(numbers))),
      selected: $selected.length ? +gatherer._get_text($selected) : 1
    };
  };

}).call(this);
