// Generated by CoffeeScript 1.7.1
(function() {
  var cheerio, gatherer, url, _,
    __slice = [].slice;

  cheerio = require('cheerio');

  _ = require('underscore');

  url = require('url');

  gatherer = require('./gatherer');

  module.exports = function($container) {
    var $links, $selected, numbers;
    $links = $container.children('a');
    $selected = $links.filter('[style="text-decoration:underline;"]');
    numbers = _.map($links, function(el) {
      return +url.parse(cheerio(el).attr('href'), true).query.page + 1;
    });
    return {
      min: _.min([1].concat(__slice.call(numbers))),
      max: _.max([1].concat(__slice.call(numbers))),
      selected: $selected.length ? +gatherer._get_text($selected) : 1
    };
  };

}).call(this);
