// Generated by CoffeeScript 1.6.2
(function() {
  var gatherer, name, tutor, _i, _len, _ref;

  gatherer = require('./gatherer');

  tutor = module.exports;

  _ref = ['formats', 'set', 'sets', 'types'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    name = _ref[_i];
    tutor[name] = gatherer[name];
  }

  tutor.card = function(details, callback) {
    var card, get, languages, legality, versions;

    switch (typeof details) {
      case 'number':
        details = {
          id: details
        };
        break;
      case 'string':
        details = {
          name: details
        };
    }
    card = languages = legality = versions = null;
    get = function(fn) {
      return function(err, data) {
        fn(data);
        if (err) {
          callback(err);
          return callback = function() {};
        } else if ((card != null) && (languages != null) && (legality != null) && (versions != null)) {
          card.languages = languages;
          card.legality = legality;
          card.versions = versions;
          return callback(null, card);
        }
      };
    };
    gatherer.card(details, get(function(data) {
      return card = data;
    }));
    gatherer.languages(details, get(function(data) {
      return languages = data;
    }));
    return gatherer.printings(details, get(function(data) {
      return legality = data.legality, versions = data.versions, data;
    }));
  };

}).call(this);
