exports[name] = code for [code, name] in [
  ['de',    'German']
  ['en',    'English']
  ['es',    'Spanish']
  ['fr',    'French']
  ['it',    'Italian']
  ['ja',    'Japanese']
  ['kr',    'Korean']
  ['pt-BR', 'Portuguese']
  ['pt-BR', 'Portuguese (Brazil)']
  ['ru',    'Russian']
  ['zh-CN', 'Chinese Traditional']
  ['zh-TW', 'Chinese Simplified']
]
